spring.application.name=Webdahoacuong

# ===============================
# DATABASE
# ===============================
# ===============================
# DATABASE
# ===============================

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true

spring.datasource.username=postgres.jagjlvvpktaonmqpriic

spring.datasource.password=Namquang123@

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SERVER
# ===============================
server.address=0.0.0.0
server.port=${SERVER_PORT:4491}

# ===============================
# JWT
# ===============================
security.jwt.secret=${JWT_SECRET:4567890poiuytrewqlkjhgfdsamnbvcxz0987654321qwertyuiopasdfghjklzxcvbnm}
security.jwt.expiration-seconds=${JWT_EXP_SECONDS:86400}
security.jwt.issuer=${JWT_ISSUER:dahoacuong}

# ===============================
# FILE UPLOAD
# ===============================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.security=DEBUG
